// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DataAccess.DataContext.Entities
{
    public partial class Appusers
    {
        public Appusers()
        {
            Authtokens = new HashSet<Authtokens>();
        }

        public Guid Id { get; set; }
        public string Username { get; set; }
        public Guid? RoleId { get; set; }
        public byte[] PasswordHash { get; set; }
        public byte[] PasswordSalt { get; set; }
        public string Title { get; set; }
        public string Fname { get; set; }
        public string Lname { get; set; }
        public DateTime? BirthDate { get; set; }
        public string Email { get; set; }
        public string MobilePhone { get; set; }
        public bool? IsActive { get; set; }
        public bool? IsForceChangePwd { get; set; }
        public int LoginAttemptCount { get; set; }
        public DateTime? LastLogin { get; set; }
        public DateTime? LastChangePwd { get; set; }
        public DateTime? PasswordExpireDate { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public DateTime? ModifiedDate { get; set; }

        public virtual Approles Role { get; set; }
        public virtual ICollection<Authtokens> Authtokens { get; set; }
    }
}